EF01MA01 = 'Utilizar números naturais como indicador de quantidade ou de ordem em diferentes situações cotidianas e reconhecer situações em que os números não indicam contagem nem ordem, mas sim código de identificação.'
EF01MA02 = 'Contar de maneira exata ou aproximada, utilizando diferentes estratégias como o pareamento e outros agrupamentos.'
EF01MA03 = 'Estimar e comparar quantidades de objetos de dois conjuntos (em torno de 20 elementos), por estimativa e/ou por correspondência (um a um, dois a dois) para indicar “tem mais”, “tem menos” ou “tem a mesma quantidade”'
EF01MA04 = 'Contar a quantidade de objetos de coleções até 100 unidades e apresentar o resultado por registros verbais e simbólicos, em situações de seu interesse, como jogos, brincadeiras, materiais da sala de aula, entre outros.'
EF01MA05 = 'Comparar números naturais de até duas ordens em situações cotidianas, com e sem suporte da reta numérica.'
EF01MA06 = 'Construir fatos básicos da adição e utilizá-los em procedimentos de cálculo para resolver problemas.'
EF01MA09 = 'Organizar e ordenar objetos familiares ou representações por figuras, por meio de atributos, tais como cor, forma e medida'
EF01MA11 = 'Descrever a localização de pessoas e de objetos no espaço em relação à sua própria posição, utilizando termos como à direita, à esquerda, em frente, atrás'
EF01MA11aTO = 'Descrever a localização de pessoas e de objetos no espaço em relação à sua própria posição, utilizando termos como à direita, à esquerda, em frente, atrás.'
EF01MA11bTO = 'Reconhecer noções de distância: perto, longe, tendo como referência o próprio corpo.'
EF01MA12 = 'Descrever a localização de pessoas e de objetos no espaço segundo um dado ponto de referência, compreendendo que, para a utilização de termos que se referem à posição, como direita, esquerda, em cima, em baixo, é necessário explicitar-se o referencial.'
EF01MA12aTO = 'Descrever a localização de pessoas e de objetos no espaço segundo um dado ponto de referência, compreendendo que, para a utilização de termos que se referem à posição, como direita, esquerda, em cima, em baixo, é necessário explicitar-se o referencial.'
EF01MA12bTO= 'Reconhecer por meio de jogos e brincadeiras, direção, posição e sentido (em cima, embaixo, perto, longe, a direita, a esquerda, ao lado, em frente, atrás, primeiro, último).'
EF01MA20 = 'Classificar eventos envolvendo o acaso, tais como “acontecerá com certeza”, “talvez aconteça” e “é impossível acontecer”, em situações do cotidiano.'
totalgeral = 'Pontuação geral da turma lenvando em conta todas as habilidades avaliadas'
EF02MA01 = 'Comparar e ordenar números naturais (até a ordem de centenas) pela compreensão de características do sistema de numeração decimal (valor posicional e função do zero).'
EF02MA02 = 'Fazer estimativas por meio de estratégias diversas a respeito da quantidade de objetos de coleções e registrar o resultado da contagem desses objetos (até 1000 unidades).'
EF02MA03 = 'Comparar quantidades de objetos de dois conjuntos, por estimativa e/ou por correspondência (um a um, dois a dois, entre outros), para indicar “tem mais”, “tem menos” ou “tem a mesma quantidade”, indicando, quando for o caso, quantos a mais e quantos a menos'
EF02MA05 = 'Construir fatos básicos da adição e subtração e utilizá-los no cálculo mental ou escrito.'
EF02MA06 = 'Resolver e elaborar problemas de adição e de subtração, envolvendo números de até três ordens, com os significados de juntar, acrescentar, separar, retirar, utilizando estratégias pessoais ou convencionais.'
EF02MA09 = 'Construir sequências de números naturais em ordem crescente ou decrescente a partir de um número qualquer, utilizando uma regularidade estabelecida.'
EF02MA12 = 'Identificar e registrar, em linguagem verbal ou não verbal, a localização e os deslocamentos de pessoas e de objetos no espaço, considerando mais de um ponto de referência, e indicar as mudanças de direção e de sentido (para frente, para trás, para direita e para esquerda).'
EF02MA18 = 'Indicar a duração de intervalos de tempo entre duas datas, como dias da semana e meses do ano, utilizando calendário, para planejamentos e organização de agenda.'
EF02MA19 = 'Medir a duração de um intervalo de tempo por meio de relógio digital e registrar o horário do início e do fim do intervalo.'
EF02MA21 = 'Classificar resultados de eventos cotidianos aleatórios como “pouco prováveis”, “muito prováveis”, “improváveis” e “impossíveis”.'
EF03MA01 = 'Ler, escrever e comparar números naturais de até a ordem de unidade de milhar, estabelecendo relações entre os registros numéricos e em língua materna.'
EF03MA02 = 'Identificar características do sistema de numeração decimal, utilizando a composição e a decomposição de número natural de até quatro ordens.'
EF03MA05 = 'Utilizar diferentes procedimentos de cálculo mental e escrito para resolver problemas significativos envolvendo adição e subtração com números naturais.'
EF03MA07 = 'Resolver e elaborar problemas de multiplicação (por 2, 3, 4, 5 e 10) com os significados de adição de parcelas iguais e elementos apresentados em disposição retangular, utilizando diferentes estratégias de cálculo e registros.'
EF03MA10 = 'Identificar regularidades em sequências ordenadas de números naturais, resultantes da realização de adições ou subtrações sucessivas, por um mesmo número, descrever uma regra de formação da sequência e determinar elementos faltantes ou seguintes.'
EF03MA15 = 'Classificar e comparar figuras planas (triângulo, quadrado, retângulo, trapézio e paralelogramo) em relação a seus lados (quantidade, posições relativas e comprimento) e vértices.'
EF03MA17 = 'Reconhecer que o resultado de uma medida depende da unidade de medida utilizada'
EF03MA18 = 'Escolher a unidade de medida e o instrumento mais apropriado para medições de comprimento, tempo e capacidade.'
EF03MA19 = 'Estimar, medir e comparar comprimentos, utilizando unidades de medida não padronizadas e padronizadas mais usuais (metro, centímetro e milímetro) e diversos instrumentos de medida.'
EF04MA01 = 'Ler, escrever e ordenar números naturais até a ordem de dezenas de milhar.'
EF04MA01TO = 'Conhecer o Sistema de Numeração Romano alfabético e posicional, suas regras de composição, leitura, escrita e sua utilização em nosso dia a dia.'
EF04MA02 = 'Mostrar, por decomposição e composição, que todo número natural pode ser escrito por meio de adições e multiplicações por potências de dez, para compreender o sistema de numeração decimal e desenvolver estratégias de cálculo.'
EF04MA08 = 'Resolver, com o suporte de imagem e/ou material manipulável, problemas simples de contagem, como a determinação do número de agrupamentos possíveis ao se combinar cada elemento de uma coleção com todos os elementos de outra, utilizando estratégias e formas de registro pessoais.'
EF04MA13 = 'Reconhecer, por meio de investigações, utilizando a calculadora quando necessário, as relações inversas entre as operações de adição e de subtração e de multiplicação e de divisão, para aplicá-las na resolução de problemas.'
EF04MA17 = 'Associar prismas e pirâmides a suas planificações e analisar, nomear e comparar seus atributos, estabelecendo relações entre as representações planas e espaciais.'
EF04MA20 = 'Medir e estimar comprimentos (incluindo perímetros), massas e capacidades, utilizando unidades de medida padronizadas mais usuais, valorizando e respeitando a cultura local.'
EF04MA22 = 'Ler e registrar medidas e intervalos de tempo em horas, minutos e segundos em situações relacionadas ao seu cotidiano, como informar os horários de início e término de realização de uma tarefa e sua duração.'
EF04MA27 = 'Analisar dados apresentados em tabelas simples ou de dupla entrada e em gráficos de colunas ou pictóricos, com base em informações das diferentes áreas do conhecimento, e produzir texto com a síntese de sua análise.'
EF05MA01 = 'Ler, escrever e ordenar números naturais até a ordem das centenas de milhar com compreensão das principais características do sistema de numeração decimal.'
EF05MA04 = 'Identificar frações equivalentes'
EF05MA05 = 'Comparar e ordenar números racionais positivos (representações fracionária e decimal), relacionando-os a pontos na reta numérica.'
EF05MA10 = 'Concluir, por meio de investigações, que a relação de igualdade existente entre dois membros permanece ao adicionar, subtrair, multiplicar ou dividir cada um desses membros por um mesmo número, para construir a noção de equivalência.'
EF05MA11 = 'Resolver e elaborar problemas cuja conversão em sentença matemática seja uma igualdade com uma operação em que um dos termos é desconhecido.'
EF05MA17 = 'Reconhecer, nomear e comparar polígonos, considerando lados, vértices e ângulos, e desenhá-los, utilizando material de desenho ou tecnologias digitais'
EF05MA19 = 'Resolver e elaborar problemas envolvendo medidas das grandezas comprimento, área, massa, tempo, temperatura e capacidade, recorrendo a transformações entre as unidades mais usuais em contextos socioculturais.'
EF05MA24 = 'Interpretar dados estatísticos apresentados em textos, tabelas e gráficos (colunas ou linhas), referentes a outras áreas do conhecimento ou a outros contextos, como saúde e trânsito, e produzir textos com o objetivo de sintetizar conclusões'
EF05MA25 = 'Realizar pesquisa envolvendo variáveis categóricas e numéricas, organizar dados coletados por meio de tabelas, gráficos de colunas, pictóricos e de linhas, com e sem uso de tecnologias digitais, e apresentar texto escrito sobre a finalidade da pesquisa e a síntese dos resultados'
EF06MA01 = 'Comparar, ordenar, ler e escrever números naturais e números racionais cuja representação decimal é finita, fazendo uso da reta numérica.'
EF06MA03 = 'Resolver e elaborar problemas que envolvam cálculos (mentais ou escritos, exatos ou aproximados) com números naturais, por meio de estratégias variadas, com compreensão dos processos neles envolvidos com e sem uso de calculadora.'
EF06MA04 = 'Construir algoritmo em linguagem natural e representá-lo por fluxograma que indique a resolução de um problema simples (por exemplo, se um número natural qualquer é par).'
EF06MA05 = 'Classificar números naturais em primos e compostos, estabelecer relações entre números, expressas pelos termos “é múltiplo de”, “é divisor de”, “é fator de”, e estabelecer, por meio de investigações, critérios de divisibilidade por 2, 3, 4, 5, 6, 8, 9, 10, 100 e 1000'
EF06MA06 = 'Resolver e elaborar problemas que envolvam as ideias de múltiplo e de divisor'
EF06MA14 = 'Reconhecer que a relação de igualdade matemática não se altera ao adicionar, subtrair, multiplicar ou dividir os seus dois membros por um mesmo número e utilizar essa noção para determinar valores desconhecidos na resolução de problemas. Problemas que tratam da partição de um todo em duas partes desiguais, envolvendo razões entre as partes e entre uma das partes e o todo.'
EF06MA18 = 'Reconhecer, nomear e comparar polígonos, considerando lados, vértices e ângulos, e classificá-los em regulares e não regulares, tanto em suas representações no plano como em faces de poliedros.'
EF06MA19 = 'Identificar características dos triângulos e classificá-los em relação às medidas dos lados e dos ângulos.'
EF06MA20 = 'Identificar características dos quadriláteros, classificá-los em relação a lados e a ângulos e reconhecer a inclusão e a intersecção de classes entre eles.'
EF06MA25 = 'Reconhecer a abertura do ângulo como grandeza associada às figuras geométricas.'
EF06MA26 = 'Resolver problemas que envolvam a noção de ângulo em diferentes contextos e em situações reais, como ângulo de visão.'
EF06MA27 = 'Determinar medidas da abertura de ângulos, por meio de transferidor e/ ou tecnologias digitais.'
EF06MA33 = 'Planejar e coletar dados de pesquisa referente a práticas sociais escolhidas pelos estudantes e fazer uso de planilhas eletrônicas para registro, representação e interpretação das informações, em tabelas, vários tipos de gráficos e texto.'
EF06MA33aTO = 'Ser capaz de planejar e coletar dados de pesquisa referente às práticas sociais da vivência cotidiana escolhidas pelos estudantes.'
EF06MA33bTO = 'Fazer uso de planilhas eletrônicas para registro, representação e interpretação das informações, em tabelas, listas, vários tipos de gráficos e texto.'
EF07MA01 = 'Resolver e elaborar problemas com números naturais, envolvendo as noções de divisor e de múltiplo, podendo incluir máximo divisor comum ou mínimo múltiplo comum, por meio de estratégias diversas, sem a aplicação de algoritmos.'
EF07MA03 = 'Comparar e ordenar números inteiros em diferentes contextos, incluindo o histórico, associá-los a pontos da reta numérica e utilizá-los em situações que envolvam adição e subtração.'
EF07MA04 = 'Resolver e elaborar problemas que envolvam operações com números inteiros'
EF07MA13 = 'Compreender a ideia de variável, representada por letra ou símbolo, para expressar relação entre duas grandezas, diferenciando-a da ideia de incógnita.'
EF07MA14 = 'Classificar sequências em recursivas e não recursivas, reconhecendo que o conceito de recursão está presente não apenas na matemática, mas também nas artes e na literatura.'
EF07MA15 = 'Utilizar a simbologia algébrica para expressar regularidades encontradas em sequências numéricas.'
EF07MA19 = 'Realizar transformações de polígonos representados no plano cartesiano, decorrentes da multiplicação das coordenadas de seus vértices por um número inteiro'
EF07MA20 = 'Reconhecer e representar, no plano cartesiano, o simétrico de figuras em relação aos eixos e à origem.'
EF07MA21 = 'Reconhecer e construir figuras obtidas por simetrias de translação, rotação e reflexão, usando instrumentos de desenho ou softwares de geometria dinâmica e vincular esse estudo a representações planas de obras de arte, elementos arquitetônicos, entre outros'
EF07MA21aTO = 'Reconhecer e construir figuras obtidas por simetrias de translação, rotação e reflexão, usando instrumentos de desenho ou softwares de geometria dinâmica.'
EF07MA21bTO = 'Explorar objetos do mundo físico, de obras de artes, pinturas, desenhos, esculturas e artesanatos fazendo conexões com outras áreas do conhecimento.'
EF07MA29 = 'Resolver e elaborar problemas que envolvam medidas de grandezas inseridas em contextos oriundos de situações cotidianas ou de outras áreas do conhecimento, reconhecendo que toda medida empírica é aproximada.'
EF07MA36 = 'Planejar e realizar pesquisa envolvendo tema da realidade social, identificando a necessidade de ser censitária ou de usar amostra, e interpretar os dados para comunicá-los por meio de relatório escrito, tabelas e gráficos, com o apoio de planilhas eletrônicas.'
EF08MA02 = 'Resolver e elaborar problemas usando a relação entre potenciação e radiciação, para representar uma raiz como potência de expoente fracionário.'
EF08MA01 = 'Efetuar cálculos com potências de expoentes inteiros e aplicar esse conhecimento na representação de números em notação científica.'
EF08MA06 = 'Resolver e elaborar problemas que envolvam cálculo do valor numérico de expressões algébricas, utilizando as propriedades das operações'
EF08MA15 = 'Construir, utilizando instrumentos de desenho ou softwares de geometria dinâmica, mediatriz, bissetriz, ângulos de 90°, 60°, 45° e 30° e polígonos regulares.'
EF08MA16 = 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um hexágono regular de qualquer área, a partir da medida do ângulo central e da utilização de esquadros e compasso.'
EF08MA12 = 'Identificar a natureza da variação de duas grandezas, diretamente, inversamente proporcionais ou não proporcionais, expressando a relação existente por meio de sentença algébrica e representá-la no plano cartesiano.'
EF08MA13 = 'Resolver e elaborar problemas que envolvam grandezas diretamente ou inversamente proporcionais, por meio de estratégias variadas.'
EF08MA26 = 'Selecionar razões de diferentes naturezas (física, ética ou econômica), que justificam a realização de pesquisas amostrais e não censitárias, e reconhecer que a seleção da amostra pode ser feita de diferentes maneiras (amostra casual simples, sistemática e estratificada).'
EF08MA27 = 'Planejar e executar pesquisa amostral, selecionando uma técnica de amostragem adequada, e escrever relatório que contenha os gráficos apropriados para representar os conjuntos de dados, destacando aspectos como as medidas de tendência central, a amplitude e as conclusões.'
EF08MA24 = 'Classificar as frequências de uma variável contínua de uma pesquisa em classes, de modo que resumam os dados de maneira adequada para a tomada de decisões.'
EF09MA01 = 'Reconhecer que, uma vez fixada uma unidade de comprimento, existem segmentos de reta cujo comprimento não é expresso por número racional (como as medidas de diagonais de um polígono e alturas de um triângulo, quando se toma a medida de cada lado como unidade).'
EF09MA01aTO = 'Reconhecer que, uma vez fixada uma unidade de comprimento, existem segmentos de reta cujo comprimento não é expresso por número racional (como as medidas de diagonais de um polígono e alturas de um triângulo, quando se toma a medida de cada lado como unidade).'
EF09MA01bTO = 'Representar na reta numérica os números Reais e estabelecer critérios de comparação e ordenação.'
EF09MA02 = 'Reconhecer um número irracional como um número real cuja representação decimal é infinita e não periódica, e estimar a localização de alguns deles na reta numérica.'
EF09MA02aTO = 'Reconhecer um número irracional como um número real cuja representação decimal é infinita e não periódica'
EF09MA02bTO = 'Representar e estimar a localização dos números irracionais na reta numérica.'
EF09MA03 = 'Efetuar cálculos com números reais, inclusive potências com expoentes fracionários.'
EF09MA03aTO = 'Efetuar cálculos com números reais, inclusive potências com expoentes fracionários.'
EF09MA03bTO = 'Efetuar cálculos com números reais utilizando radicais.'
EF09MA04 = 'Resolver e elaborar problemas com números reais, inclusive em notação científica, envolvendo diferentes operações.'
EF09MA09 = 'Compreender os processos de fatoração de expressões algébricas, com base em suas relações com os produtos notáveis, para resolver e elaborar problemas que possam ser representados por equações polinomiais do 2º grau.'
EF09MA09aTO = 'Compreender os processos de fatoração de expressões algébricas, com base em suas relações com os produtos notáveis.'
EF09MA09bTO = 'Elaborar problemas que possam ser representados por equações polinomiais do 2º grau.'
EF09MA10 = 'Demonstrar relações simples entre os ângulos formados por retas paralelas cortadas por uma transversal.'
EF09MA17 = 'Reconhecer vistas ortogonais de figuras espaciais e aplicar esse conhecimento para desenhar objetos em perspectiva.'
EF09MA23 = 'Planejar e executar pesquisa amostral envolvendo tema da realidade social e comunicar os resultados por meio de relatório contendo avaliação de medidas de tendência central e da amplitude, tabelas e gráficos adequados, construídos com o apoio de planilhas eletrônicas.'
EF09MA23aTO = 'Planejar e executar pesquisa amostral envolvendo tema da realidade social presentes na vida cotidiana.'
EF09MA23bTO = 'Apresentar os resultados por meio de relatório contendo avaliação de medidas de tendência central e da amplitude, tabelas e gráficos adequados, construídos com o apoio de planilhas eletrônicas'














